apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getallsuburbs
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 3
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: handlers.get_all_suburbs
    packageref:
      name: httphandlers
      namespace: ""
  requestsPerPod: 1
  resources: {}
