apiVersion: fission.io/v1
kind: Function
metadata:
  name: getsuburbcrimeandweather
spec:
  environment:
    name: python
    namespace: default  # Specify the namespace if it's not the default one
  package:
    packageref:
      name: httphandlers
      namespace: default  # Specify the namespace if it's not the default one
    functionName: handlers.get_suburb_crime_and_weather
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MinScale: 3
      MaxScale: 3  # Set a non-zero MaxScale for autoscaling
      SpecializationTimeout: 120
      TargetCPUPercent: 80  # Adjust target CPU percent as necessary
      KeepWarmContainer: true
    StrategyType: execution
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  functionTimeout: 60
  idletimeout: 120

