apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: airextract
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 300
  idletimeout: 300
  package:
    functionName: airextract.main
    packageref:
      name: airextract
      namespace: ""
  requestsPerPod: 1
  resources: {}
