apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getweatherbysuburb
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 3
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: handlers.get_weather_by_suburb
    packageref:
      name: httphandlers
      namespace: ""
  requestsPerPod: 1
  resources: 
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
