apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getcrimebysuburb
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 3
      MinScale: 3
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: handlers.get_crime_by_suburb
    packageref:
      name: httphandlers
      namespace: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
