include:
- ./airextract.zip
kind: ArchiveUploadSpec
name: airextract-zip-Cv3P

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: airextract
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://airextract-zip-Cv3P
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-05T07:50:20Z"
