include:
- ./weatherdataextract.zip
kind: ArchiveUploadSpec
name: weatherdataextract-zip-VT8k

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: weatherdataextract
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://weatherdataextract-zip-VT8k
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T15:12:30Z"
