include:
- ./http_handlers/*.py
- ./http_handlers/requirements.txt
- ./http_handlers/build.sh
kind: ArchiveUploadSpec
name: http-handlers-py-tNF6

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: httphandlers
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://http-handlers-py-tNF6
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-10T05:39:40Z"
