include:
- ./mstdpostextract.zip
kind: ArchiveUploadSpec
name: mstdpostextract-zip-dTeD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mstdpostextract
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://mstdpostextract-zip-dTeD
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-10T15:24:44Z"
