include:
- ./weatherstationextract.zip
kind: ArchiveUploadSpec
name: weatherstationextract-zip-vRqI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: weatherstationextract
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://weatherstationextract-zip-vRqI
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-05T14:35:58Z"
