include:
- ./crime/crime.py
- ./crime/requirements.txt
- ./crime/build.sh
kind: ArchiveUploadSpec
name: crime-crime-py-6MFo

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getallcrime
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://crime-crime-py-6MFo
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-09T06:38:53Z"
