apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getallsuburbs
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getallsuburbs
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/suburbs
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /api/suburbs
