apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getcrimebysuburb
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getcrimebysuburb
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /crime/{suburb}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /crime/{suburb}
