apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: comparesentimentandcrime
spec:
  createingress: false
  functionref:
    functionweights: null
    name: comparesentimentandcrime
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/sentiment/{year}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /api/sentiment/{year}
