apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getweatherbysuburb
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getweatherbysuburb
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /api/weather/{suburb}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /api/weather/{suburb}
