apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getallcrime
spec:
  createingress: false
  functionref:
    functionweights: null
    name: getallcrime
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /crime
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /crime
