apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: weather-ingest
spec:
  cron: '@every 60m'
  functionref:
    functionweights: null
    name: weatherdataextract
    type: name
