include:
- ./harvesters/epa_harvester.py
kind: ArchiveUploadSpec
name: harvesters-epa-harvester-py-Y5IE

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: epaharvester-9244b708-e112-4fc4-9110-ea5d58f57474
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://harvesters-epa-harvester-py-Y5IE
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-04-30T14:08:06Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: epaharvester
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: epaharvester-9244b708-e112-4fc4-9110-ea5d58f57474
      namespace: ""
  requestsPerPod: 1
  resources: {}
