name: Python Linting with Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        # This uses a single key for caching all dependencies across multiple requirements.txt files
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies from all requirements.txt files
      run: |
        find . -name 'requirements.txt' -exec pip install -r {} \;
        pip install pylint
        pip install Flask requests

    - name: Run Pylint on all Python files
      run: |
        pylint $(git ls-files '*.py')
